rules:
  - 'quotes': ['error', 'single']
  - 'max-len': ['error', { code: 120 }]
  - 'semi': ['error', 'always']
  - 'indent': ['error', 2]
  - 'no-trailing-spaces': 'error'
  - 'eol-last': ['error', 'always']
  - 'no-multiple-empty-lines': ['error', { max: 1 }]
  - 'comma-dangle': ['error', 'always-multiline']
  - 'object-curly-spacing': ['error', 'always']

variables:
  ECMAScriptVersion: 2021
  sourceType: module

globals:
  browser: true
  node: true

envs:
  - node
